#ifndef __CHANNELOPTION_H__
#define __CHANNELOPTION_H__
enum ChannelOption
{
	OPT_BACKlOG=0,
	OPT_REUSEADDR,
	OPT_REUSEPORT,
	OPT_KEEPALIVE,
	OPT_DONTROUTE,
	OPT_SOCKETRCVBUF,
	OPT_SOCKETSENDBUF,
	OPT_SOCKETDEBUG,
	OPT_TCPNODELAY,
	OPT_TCPMAXSEG,
	OPT_READLOWWATERMARK,
	OPT_READHIGHWATERMARK,
	OPT_READIDLEKETIMEOUT,
	OPT_WRITEIDELETIMEOUT,
	OPT_ALLIDELRTIMEOUT,
	NUM_CHANNELOPTIONS
};
#endif
